[build-system]
requires = ["setuptools", "wheel"]  # Build requirements
build-backend = "setuptools.build_meta"

[project]
name = "lora_on_qwen" 
version = "1.0.0"
description = "M2 courswework project"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [
    { name = "Yilan", email = "yx423@cam.ac.uk" }
]
keywords = ["LoRA", "Large Language Model", 'Machine Learning', 'Deep Learning']
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries"
]

# Runtime dependencies
dependencies = []


[tool.setuptools.packages.find]
where = ["."]
